#!/usr/bin/env bash

# Copyright © 2019 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
prog="${0##*/}"
eval '_="${0@Q}"' 2>/dev/null || {
    printf '%s: bash >= 4.4 is required\n' "$prog" >&2
    exit 1
}
tmpdir=$(mktemp -u /tmp/rytdl.XXXXXX)
if [ $# -lt 2 ]
then
    printf 'Usage: %s HOST ARGS...\n' "$prog" >&2
    exit 1
fi
host="$1"
shift
ssh "$host" "
set -e -u
set -x
mkdir ${tmpdir@Q}
cd ${tmpdir@Q}
bash --login -c 'exec youtube-dl \"\$@\"' - ${*@Q}
"
sftp -a "$host:$tmpdir/*"
ssh "$host" "rm -rf ${tmpdir@Q}"

# vim:ts=4 sts=4 sw=4 et
